# Generated by Django 2.1.15 on 2020-04-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_persona_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
