# Generated by Django 2.1.15 on 2020-04-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200425_1104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
    ]
