# Generated by Django 2.1.15 on 2020-04-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200425_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'db_table': 'repartidor',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='entrada',
            name='estado',
            field=models.CharField(default='Abierta', max_length=50),
        ),
    ]
