# Generated by Django 2.1.15 on 2020-04-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200427_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Repartidor'),
        ),
    ]
